# Generated by Django 2.2.5 on 2019-11-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_registrarcliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=30)),
                ('apaterno', models.CharField(max_length=30)),
                ('amateno', models.CharField(max_length=30)),
                ('telefono', models.PositiveSmallIntegerField()),
                ('fech_nac', models.DateField()),
                ('email_user', models.EmailField(max_length=254)),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='Photos')),
            ],
        ),
    ]
